title: Codign Dev
author: codign
description: > # this means to ignore newlines until "show_excerpts:"
 Basit Kodlarla Eğlenceli Ve Kullanışlı Şeyler Üreten Github Sayfası. Faydalı Olması Dileğiyle...
 ilgi alanları:html,css,js,nodejs,vuejs,php,blockchain...
show_excerpts: true # Basit Kodlar
codign:
  date_format: "%b %-d, %Y"
#header_pages:

# Build settings
theme: codign
